"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['VFAmain.py']
DATA_FILES = ['gui']
OPTIONS = {
    'argv_emulation': True,
    'packages': ['httplib2', 'requests', 'selenium']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
